apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "server-power-modeler.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      {{- include "server-power-modeler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- if .Values.global }}
      {{- if or .Values.annotations .Values.global.annotations .Values.podAnnotations }}
      annotations:
      {{- with .Values.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
       {{- end }}
      {{- end }}
      {{- end }}
      labels:
        {{- include "server-power-modeler.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/part-of: non-mediation
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        {{- if or .Values.serviceAccountName .Values.global.serviceAccountName }}
      serviceAccountName: {{ template "serviceAccountName" . }}
        {{- end }}
        {{- if or .Values.podSecurityContext .Values.global.securityContext }}
      securityContext:
        {{- with .Values.podSecurityContext }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.securityContext }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- $env := dict }}
            {{- range $entry := .Values.env }}
            - name: {{ $entry.name }}
              value: {{ $entry.value | quote }}
            {{- $_ := set $env $entry.name $entry.value }}
            {{- end }}
            {{- range $entry := .Values.defaultEnv }}
            {{- if not (get $env $entry.name) }}
            - name: {{ $entry.name }}
              value: {{ $entry.value | quote }}
            {{- end }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
    {{- end }}
