# Default values for metrics-adapter-aws.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

annotations: {}
labels: {}
serviceAnnotations: {}
serviceLabels: {}
kubeAuthSecretsVolume: {}
kubeAuthSecretsVolumeMount: {}

replicaCount: 1

image:
  repository: turbonomic
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: component_type
    value: metrics-adapter-aws-cloudwatch
  - name: instance_id
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: instance_ip
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: clustermgr_host
    value: clustermgr
  - name: clustermgr_port
    value: "8080"

resources:
  limits:
    memory: 32Gi
  requests:
    memory: 384Mi
