# Default values for server-power-modeler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

annotations: {}

replicaCount: 1

image:
  repository: turbonomic
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  - name: component_type
    value: server-power-modeler
  - name: instance_id
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: HISTORY_BASE_URL
    value: http://history:8080
  - name: REPOSITORY_BASE_URL
    value: http://repository:8080
  - name: LOG_CONFIG
    value: logger.conf
  - name: ONE_SHOT_EXEC
    value: 0
  - name: SLEEP_DURATION
    value: 1440
  - name: clustermgr_host
    value: clustermgr
  - name: clustermgr_port
    value: "8080"
  - name: kafkaServers
    value: kafka:9092

resources:
  limits:
    #  cpu: 100m
    memory: 16Gi
  requests:
    #  cpu: 100m
    memory: 1Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

customizeConfigMap: false

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
