apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    zone: internal
    io.kompose.service: topology-processor
  name: {{ .Chart.Name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    zone: internal
    io.kompose.service: topology-processor
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        zone: internal
        io.kompose.service: topology-processor
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "topology_image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: JAVA_OPTS
{{- if .Values.global }}
  {{- if .Values.global.debug }}
          value: {{ .Values.global.dev_options }} {{ .Values.java.options }}
  {{- else }}
          value: {{ .Values.java.options }}
  {{- end }}
{{- else }}
          value: {{ .Values.java.options }}
{{- end }}
        - name: clustermgr_host
          value: clustermgr
        - name: clustermgr_port
          value: "8080"
        - name: clustermgr_retry_delay_sec
          value: "10"
        - name: component_type
          value: topology-processor
        - name: consul_host
          value: consul
        - name: instance_id
          value: topology-processor-1
        - name: kafkaServers
          value: kafka:9092
        - name: node_name
          value: default
        - name: realtimeTopologyContextId
          value: "777777"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            port: 8080
            path: /health
        resources:
{{ toYaml .Values.resources | indent 12 }}
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /home/turbonomic/data
          name: topology-processor
        - mountPath: /tmp
          name: topology-processor-tmpfs0
{{- if .Values.global }}
  {{- if and .Values.global.registry .Values.global.imageUsername .Values.global.imagePassword }}
      imagePullSecrets:
      - name: turbocred
  {{- end -}}
{{- end }}
      restartPolicy: Always
      securityContext:
        fsGroup: 2000
      volumes:
      - name: topology-processor
        persistentVolumeClaim:
          claimName: topology-processor
      - name: topology-processor-tmpfs0
        emptyDir: {}
  selector:
    matchLabels:
      io.kompose.service: topology-processor
---
apiVersion: v1
kind: Service
metadata:
  labels:
    zone: internal
    io.kompose.service: topology-processor
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: http-topology-processor
    port: 8080
{{- if .Values.global }}
  {{- if .Values.global.debug }}
  - name: tcp-topology-processor-debug
    port: 8000
  {{- end -}}
{{- end }}
  - name: grpc-topology-processor
    port: 9001
  selector:
    io.kompose.service: topology-processor
