{{- if .Values.global }}
  {{- if or (not .Values.global.enableExternalSecrets) (not (or .Values.global.enableEphemeralDiscoveryDumps .Values.enableEphemeralDiscoveryDumps))}}
    {{/* Use the PV legacy behavior unless both external secrets and ephemeral discovery dumps are enabled. */}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}
  {{- if or .Values.storageAnnotations .Values.global.storageAnnotations }}
  annotations:
    {{- with .Values.storageAnnotations }}
{{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.global.storageAnnotations }}
{{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
  labels:
    zone: internal
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
{{- if .Values.global }}
  {{- if .Values.global.storageSelector }}
  selector:
    matchLabels:
      partition: {{ .Release.Namespace }}-topology-processor
  {{- end }}
  {{- if .Values.global.storageClassName }}
  storageClassName: {{ .Values.global.storageClassName }}
  {{- end }}
{{- end }}
  resources:
    requests:
      storage: 3Gi
---
  {{- end }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    zone: internal
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
{{- if .Values.global }}
  {{- if or .Values.annotations .Values.global.annotations }}
      annotations:
    {{- with .Values.annotations }}
{{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.global.annotations }}
{{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
{{- end }}
      labels:
{{- include "labels" . | nindent 8 }}
        zone: internal
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/part-of: non-mediation
    spec:
{{- if .Values.global }}
  {{- if or .Values.serviceAccountName .Values.global.serviceAccountName }}
      serviceAccountName: {{ template "serviceAccountName" . }}
  {{- end }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "image" . }}
        imagePullPolicy: {{ template "pullPolicy" . }}
        env:
{{ template "java.setJVMEnvironmentOptions" . }}
{{ toYaml .Values.env | indent 8 }}
{{- if .Values.global }}
  {{- if or .Values.logtostdout .Values.global.logtostdout }}
        - name: LOG_TO_STDOUT
          value: "true"
  {{- end }}
{{- end }}
        ports:
          - containerPort: 8080
          - containerPort: 9001
        livenessProbe:
          httpGet:
            port: 8080
            path: /health
{{- include "common.getLivenessThresholds" . | indent 10 }}
        readinessProbe:
          httpGet:
            port: 8080
            path: /health
{{- include "common.getReadinessThresholds" . | indent 10 }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
{{ if .Values.global }}
  {{ if .Values.global.disableSameTrustStore }}
        - mountPath: /vault/trust
          name: topology-processor-truststore-secret
          readOnly: true
  {{- else }}
        - mountPath: /vault/trust
          name: common-truststore-secret
          readOnly: true
  {{- end }}
{{- end }}
        - mountPath: /vault/key
          name: topology-processor-keystore-secret
          readOnly: true
        - mountPath: /vault/mtlsSecrets
          name: topology-processor-mtls-secret
          readOnly: true
        - mountPath: /home/turbonomic/data
          name: topology-processor
{{- if .Values.global }}
  {{- if .Values.global.enableExternalSecrets }}
    {{/* Kubernetes secrets are enabled for encryption keys. */}}
  {{/* Kubernetes secrets are enabled for auth. */}}
        - mountPath: /home/turbonomic/data/master_keys
          name: master-key-secret
          readOnly: true
  {{/* Optionally mount the legacy encryption key to be read in as part of upgrades. */}}
        - mountPath: /home/turbonomic/data/helper_dir
          name: topology-processor-secret
          readOnly: true
  {{- end }}
{{- end }}
        - mountPath: /etc/turbonomic
          name: turbo-volume
          readOnly: true
        - mountPath: /tmp
          name: topology-processor-tmpfs0
{{- if .Values.global }}
  {{- if or .Values.dbSecretName .Values.global.dbSecretName }}
        - mountPath: /vault/secrets
          name: db-creds
          readOnly: true
  {{- end -}}
  {{- if .Values.global.registry }}
    {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
    {{- else -}}
      {{- if and .Values.global.imageUsername .Values.global.imagePassword }}
      imagePullSecrets:
      - name: turbocred
      {{- end -}}
    {{- end -}}
  {{- end -}}
  {{- with .Values.global.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.global.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.global.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.global.securityContext }}
      securityContext:
{{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
      restartPolicy: Always
      volumes:
      - name: topology-processor
{{- if .Values.global }}
  {{- if or (not .Values.global.enableExternalSecrets) (not (or .Values.global.enableEphemeralDiscoveryDumps .Values.enableEphemeralDiscoveryDumps))}}
    {{/* Use the PV legacy behavior unless both external secrets and ephemeral discovery dumps are enabled. */}}
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}
  {{- else }}
        emptyDir: {}
  {{- end }}
{{- end }}
      - name: turbo-volume
        configMap:
          name: global-properties-{{ .Release.Name }}
          optional: true
      - name: topology-processor-truststore-secret
        secret:
          secretName: topology-processor-truststore-secret
          optional: true
      - name: common-truststore-secret
        secret:
          secretName: common-truststore-secret
          optional: true
      - name: topology-processor-keystore-secret
        secret:
          secretName: topology-processor-keystore-secret
          optional: true
      - name: topology-processor-mtls-secret
        secret:
          secretName: topology-processor-mtls-secret
          optional: true
      - name: topology-processor-tmpfs0
        emptyDir: {}
{{- if .Values.global }}
  {{- if .Values.global.enableExternalSecrets }}
    {{/* Kubernetes secrets are enabled for auth. Attach one secret for the directory of secret files. */}}
      - name: master-key-secret
        secret:
          secretName: master-key-secret
          optional: true
  {{/* Optionally mount the legacy encryption key to be read in as part of upgrades. */}}
      - name: topology-processor-secret
        secret:
            secretName: topology-processor-secret
            optional: true
  {{- end }}
  {{- if or .Values.dbSecretName .Values.global.dbSecretName }}
      - name: db-creds
        secret:
          secretName: {{ template "dbSecretName" . }}
          optional: true
  {{- end }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
{{- include "serviceAnnotations" . | nindent 4 }}
  labels:
{{- include "serviceLabels" . | nindent 4 }}
    zone: internal
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - name: http-topology-processor
    port: 8080
{{- if .Values.global }}
  {{- if or .Values.debug .Values.global.debug }}
  - name: tcp-topology-processor-debug
    port: 8000
  {{- end -}}
{{- end }}
  - name: grpc-topology-processor
    port: 9001
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
