# Default values for mediation-vmm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

annotations: {}
labels: {}
serviceAnnotations: {}
serviceLabels: {}
kubeAuthSecretsVolume: {}
kubeAuthSecretsVolumeMount: {}

replicaCount: 1

image:
  repository: turbonomic
  tag: latest
  pullPolicy: IfNotPresent

javaComponentOptions: "-Dorg.eclipse.jetty.websocket.jsr356.ssl-trust-all=true
    -DLog4jContextSelector=com.vmturbo.mediation.common.context.ThreadGroupPrefixContextSelector"

env:
  - name: component_type
    value: mediation-vmm
  - name: instance_id
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: instance_ip
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: clustermgr_host
    value: clustermgr
  - name: clustermgr_port
    value: "8080"

winrm-proxy:
  enabled: false
  env:
    logLevel: info
    logPrefix: vmm
    serverWorker: 4
    krbRenewHours: 5

resources:
  limits:
    memory: 32Gi
  requests:
    memory: 384Mi
