apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    zone: dmz
    io.kompose.service: api-certs
  name: {{ .Chart.Name }}-certs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    zone: dmz
    io.kompose.service: api
  name: {{ .Chart.Name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    zone: dmz
    io.kompose.service: api
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        zone: dmz
        io.kompose.service: api
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "api_image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: JAVA_OPTS
{{- if .Values.global }}
  {{- if .Values.global.debug }}
          value: {{ .Values.global.dev_options }} {{ .Values.java.options }}
  {{- else }}
          value: {{ .Values.java.options }}
  {{- end }}
{{- else }}
          value: {{ .Values.java.options }}
{{- end }}
        - name: clustermgr_host
          value: clustermgr
        - name: clustermgr_port
          value: "8080"
        - name: clustermgr_retry_delay_sec
          value: "10"
        - name: component_type
          value: api
        - name: consul_host
          value: consul
        - name: instance_id
          value: api-1
        - name: kafkaServers
          value: kafka:9092
        - name: realtimeTopologyContextId
          value: "777777"
        - name: enableVMVirtualVolumeAspectMapper
          value: "false"
        readinessProbe:
          httpGet:
            port: 8080
            path: /health
        resources:
{{ toYaml .Values.resources | indent 12 }}
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /home/turbonomic/data
          name: api
        - mountPath: /tmp/certs
          name: api-certs
        - mountPath: /tmp
          name: api-tmpfs0
{{- if .Values.global }}
  {{- if and .Values.global.registry .Values.global.imageUsername .Values.global.imagePassword }}
      imagePullSecrets:
      - name: turbocred
  {{- end -}}
{{- end }}
      restartPolicy: Always
      securityContext:
        fsGroup: 2000
      volumes:
      - name: api
        persistentVolumeClaim:
          claimName: api
      - name: api-certs
        persistentVolumeClaim:
          claimName: api-certs
      - name: api-tmpfs0
        emptyDir: {}
  selector:
    matchLabels:
      io.kompose.service: api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    zone: dmz
    io.kompose.service: api
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: http-api
    port: 8080
  - name: https-api
    port: 9443
{{- if .Values.global }}
  {{- if .Values.global.debug }}
  - name: tcp-api-debug
    port: 8000
  {{- end -}}
{{- end }}
  - name: grpc-api
    port: 9001
  selector:
    io.kompose.service: api
