{{ if .Values.global }}
  {{ if and (not .Values.global.elk) (not .Values.global.externalSyslog) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-auditlogdata
  {{- if or .Values.storageAnnotations .Values.global.storageAnnotations }}
  annotations:
    {{- with .Values.storageAnnotations }}
{{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.global.storageAnnotations }}
{{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
  labels:
    zone: internal
    app.kubernetes.io/name: {{ .Chart.Name }}-auditlogdata
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
{{- if .Values.global }}
  {{- if .Values.global.storageSelector }}
  selector:
    matchLabels:
      partition: {{ .Release.Namespace }}-rsyslog-auditlogdata
  {{- end }}
  {{- if .Values.global.storageClassName }}
  storageClassName: {{ .Values.global.storageClassName }}
  {{- end }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.auditsize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-syslogdata
  {{- if or .Values.storageAnnotations .Values.global.storageAnnotations }}
  annotations:
    {{- with .Values.storageAnnotations }}
{{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.global.storageAnnotations }}
{{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
  labels:
    zone: internal
    app.kubernetes.io/name: {{ .Chart.Name }}-syslogdata
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
{{- if .Values.global }}
  {{- if .Values.global.storageSelector }}
  selector:
    matchLabels:
      partition: {{ .Release.Namespace }}-rsyslog-syslogdata
  {{- end }}
  {{- if .Values.global.storageClassName }}
  storageClassName: {{ .Values.global.storageClassName }}
  {{- end }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.logsize }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  annotations:
{{- with .Values.tunnel }}
{{- if .expose }}
{{- include "skupperExpose" . | nindent 4 }}
{{- end }}
{{- end }}
  labels:
    zone: internal
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
{{- if .Values.global }}
  {{- if or .Values.annotations .Values.global.annotations }}
      annotations:
    {{- with .Values.annotations }}
{{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.global.annotations }}
{{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
{{- end }}
      labels:
{{- include "labels" . | nindent 8 }}
        zone: internal
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
{{- if .Values.global }}
  {{- if or .Values.serviceAccountName .Values.global.serviceAccountName }}
      serviceAccountName: {{ template "serviceAccountName" . }}
  {{- end }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
{{- if .Values.global }}
  {{- if .Values.global.customImageNames }}
        image: {{ template "syslog_image" . }}
  {{- else }}
        image: {{ template "image" . }}
  {{- end }}
        imagePullPolicy: {{ template "pullPolicy" . }}
{{- end }}
{{ if .Values.env }}
        env:
{{ toYaml .Values.env | indent 8 }}
{{ end }}
        ports:
        - containerPort: 2514
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 2514
{{- include "common.getLivenessThresholds" . | indent 10 }}
        readinessProbe:
          tcpSocket:
            port: 2514
{{- include "common.getReadinessThresholds" . | indent 10 }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /etc/turbonomic
          name: turbo-volume
          readOnly: true
        - mountPath: /home/vmtsyslog
          name: rsyslog-syslogdata
        - mountPath: /var/log/turbonomic
          name: rsyslog-auditlogdata
        - mountPath: /tmp
          name: rsyslog-tmpfs0
{{- if .Values.global }}
  {{- if .Values.global.registry }}
    {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
    {{- else -}}
      {{- if and .Values.global.imageUsername .Values.global.imagePassword }}
      imagePullSecrets:
      - name: turbocred
      {{- end -}}
    {{- end -}}
  {{- end -}}
  {{- with .Values.global.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.global.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.global.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.global.securityContext }}
      securityContext:
{{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
      restartPolicy: Always
      volumes:
      - name: turbo-volume
        configMap:
          name: global-properties-{{ .Release.Name }}
          optional: true
      - name: rsyslog-syslogdata
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-syslogdata
      - name: rsyslog-auditlogdata
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-auditlogdata
      - name: rsyslog-tmpfs0
        emptyDir: {}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{ end }}
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
{{- include "serviceAnnotations" . | nindent 4 }}
  labels:
{{- include "serviceLabels" . | nindent 4 }}
    zone: internal
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
{{- if .Values.global }}
  {{- if .Values.global.elk }}
  type: ExternalName
  externalName: logstash.{{ .Release.Namespace }}.svc.cluster.local
  {{- else if .Values.global.externalSyslog }}
  type: ExternalName
  externalName: {{ .Values.global.externalSyslog }}
  {{- end -}}
{{- end }}
  ports:
  - name: tcp-rsyslog
    port: 2514
  - name: http-rsyslog
    port: 8080
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
