apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    zone: secure
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
{{- if .Values.global }}
  {{- if or .Values.annotations .Values.global.annotations }}
      annotations:
    {{- with .Values.annotations }}
{{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.global.annotations }}
{{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
{{- end }}
      labels:
{{- include "labels" . | nindent 8 }}
        zone: secure
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
{{- if .Values.global }}
  {{- if or .Values.serviceAccountName .Values.global.serviceAccountName }}
      serviceAccountName: {{ template "serviceAccountName" . }}
  {{- end }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
{{- if .Values.global }}
  {{- if .Values.global.customImageNames }}
        image: {{ template "metrics-processor_image" . }}
  {{- else }}
        image: {{ template "image" . }}
  {{- end }}
        imagePullPolicy: {{ template "pullPolicy" . }}
{{- end }}
        env:
{{ template "java.setJVMEnvironmentOptions" . }}
{{ toYaml .Values.env | indent 8 }}
{{- if .Values.global }}
  {{- if or .Values.logtostdout .Values.global.logtostdout }}
        - name: LOG_TO_STDOUT
          value: "true"
  {{- end }}
{{- end }}
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            path: /health
          periodSeconds: 60
          failureThreshold: 60
        readinessProbe:
          httpGet:
            port: 8080
            path: /health
        resources:
{{ toYaml .Values.resources | indent 12 }}
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /home/turbonomic/data
          name: metrics-processor-data
        - mountPath: /etc/turbonomic
          name: turbo-volume
          readOnly: true
        - mountPath: /tmp
          name: metrics-processor-tmpfs0
{{- if .Values.global }}
  {{- if .Values.global.enableExternalSecrets }}
    {{/* Kubernetes secrets are enabled for encryption keys. */}}
  {{/* Kubernetes secrets are enabled for auth. */}}
        - mountPath: /home/turbonomic/data/master_keys
          name: master-key-secret
          readOnly: true
  {{/* Optionally mount the legacy encryption key to be read in as part of upgrades. */}}
        - mountPath: /home/turbonomic/data/helper_dir
          name: topology-processor-secret
          readOnly: true
  {{- end }}
{{- end }}

{{- if .Values.global }}
    {{- if .Values.global.jwtAuthenticationEnabled }}
        {{- include "kubeAuthSecretsVolumeMount" . | indent 8  -}}
    {{ end }}
{{ end }}
{{- if .Values.global }}
  {{- if .Values.global.registry }}
    {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
    {{- else -}}
      {{- if and .Values.global.imageUsername .Values.global.imagePassword }}
      imagePullSecrets:
      - name: turbocred
      {{- end -}}
    {{- end -}}
  {{- end -}}
  {{- with .Values.global.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.global.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.global.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
      restartPolicy: Always
      securityContext:
        fsGroup: {{ .Values.global.securityContext.fsGroup | default 65534 }}
      volumes:
      - name: metrics-processor-data
{{- if .Values.global }}
  {{- if not .Values.global.enableExternalSecrets}}
    {{/* Use the PV legacy behavior unless external secrets are enabled. */}}
        persistentVolumeClaim:
          claimName: topology-processor
  {{- else }}
        emptyDir: {}
  {{- end }}
{{- end }}
      - name: turbo-volume
        configMap:
          name: global-properties-{{ .Release.Name }}
          optional: true
      - name: metrics-processor-tmpfs0
        emptyDir: {}
{{- if .Values.global }}
  {{- if .Values.global.enableExternalSecrets }}
    {{/* Kubernetes secrets are enabled for auth. Attach one secret for the directory of secret files. */}}
      - name: master-key-secret
        secret:
          secretName: master-key-secret
          optional: true
  {{/* Optionally mount the legacy encryption key to be read in as part of upgrades. */}}
      - name: topology-processor-secret
        secret:
            secretName: topology-processor-secret
            optional: true
  {{- end }}
{{- end }}
{{- if .Values.global }}
    {{- if .Values.global.jwtAuthenticationEnabled }}
        {{- include "kubeAuthSecretsVolume" . | indent 6 -}}
    {{ end }}
{{ end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}