apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
{{- include "serviceAnnotations" . | nindent 4 }}
  labels:
{{- include "serviceLabels" . | nindent 4 }}
    zone: secure
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - name: http-metrics-processor
    port: 8080
{{- if .Values.global }}
  {{- if or .Values.debug .Values.global.debug }}
  - name: tcp-metrics-processor-debug
    port: 8000
  {{- end -}}
{{- end }}
  - name: grpc-metrics-processor
    port: 9001
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
