{
 "title": "gRPC Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,15m,20m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "service", "label": "component", "query": "label_values(service)" },
   { "name": "grpc_service", "label": "endpoint", "query": "label_values(grpc_service)" },
   { "name": "grpc_method", "label": "method", "query": "label_values(grpc_method)" }
  ]
 },
 "panels": [
  {
   "title": "Response latency of gRPCs (sec)",
   "type": "graph",
   "description": "Histogram of response latency (seconds) of gRPC that had been application-level handled by the server.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(grpc_server_handled_latency_seconds_sum{service=~\"$service\",grpc_service=~\"$grpc_service\",grpc_method=~\"$grpc_method\"}[$interval])",
     "legendFormat": "{{service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPCs handled",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(grpc_server_handled_total{service=~\"$service\",grpc_service=~\"$grpc_service\",grpc_method=~\"$grpc_method\"}[$interval])",
     "legendFormat": "{{service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC messages sent",
   "type": "graph",
   "description": "Total number of stream messages sent by the server.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(grpc_server_msg_sent_total{service=~\"$service\",grpc_service=~\"$grpc_service\",grpc_method=~\"$grpc_method\"}[$interval])",
     "legendFormat": "{{service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC messages received",
   "type": "graph",
   "description": "Total number of stream messages received from the client.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(grpc_server_msg_received_total{service=~\"$service\",grpc_method=~\"$grpc_method\"}[$interval])",
     "legendFormat": "{{service}}.{{grpc_method}}"
    }
   ]
  }
 ]
}