{
 "title": "Kubernetes namespaces individual",
 "description": "Monitor resources inside a kubernetes namespace",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "CPU (millicores)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace$\"}[5m]) * 1000) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory (bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",container_name!=\"\",namespace=~\"^$namespace$\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"^$namespace$\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"^$namespace$\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}