{
 "title": "Repository Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Repository store source topology",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(repo_update_topology_duration_seconds_sum{topology_type=\"source\"}[10m])"
    }
   ]
  },
  {
   "title": "Repository fetch global supply chain",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(repo_global_supply_chain_duration_seconds_sum[10m])"
    }
   ]
  },
  {
   "title": "Repository fetch single-source supply chain (Datacenter start)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ]
  },
  {
   "title": "Repository GC Collection Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_gc_collection_seconds_sum{service=\"repository\"}[10m])"
    }
   ]
  },
  {
   "title": "Repository memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{service=\"repository\"}"
    }
   ]
  }
 ]
}