{
 "title": "System Latencies",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Supply Chain Latency",
   "type": "graph",
   "description": "See https://vmturbo.atlassian.net/wiki/display/Home/XL+200k+Performance+Thought for what this means.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "end-to-end latency" }
   ],
   "targets": [
    {
     "expr": "delta(tp_discovery_duration_seconds_sum{source=\"top\"}[10m])"
    },
    {
     "expr": "delta(tp_broadcast_duration_seconds_sum{source='topology-processor'}[10m])"
    },
    {
     "expr": "delta(repo_update_topology_duration_seconds_sum{source='repository',topology_type='source'}[10m])"
    },
    {
     "expr": "delta(repo_global_supply_chain_duration_seconds_sum[10m])"
    }
   ]
  },
  {
   "title": "Action Latency",
   "type": "graph",
   "description": "See https://vmturbo.atlassian.net/wiki/display/Home/XL+200k+Performance+Thought for what this means.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s", "label": "end-to-end latency" }
   ],
   "targets": [
    {
     "expr": "delta(tp_discovery_duration_seconds_sum{source='topology-processor'}[10m])"
    },
    {
     "expr": "delta(tp_broadcast_duration_seconds_sum{source='topology-processor'}[10m])"
    },
    {
     "expr": "delta(mkt_analysis_duration_seconds_sum[10m])"
    },
    {
     "expr": "delta(ao_populate_store_duration_seconds_sum{store_type='Live'}[10m])"
    }
   ]
  },
  {
   "title": "Source Topology Stats Latency",
   "type": "graph",
   "description": "See https://vmturbo.atlassian.net/wiki/display/Home/XL+200k+Performance+Thought for what this means.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s", "label": "end-to-end latency" }
   ],
   "targets": [
    {
     "expr": "delta(ao_populate_store_duration_seconds_sum{store_type='Live'}[10m])"
    },
    {
     "expr": "delta(tp_broadcast_duration_seconds_sum{source='topology-processor'}[10m])"
    },
    {
     "expr": "delta(history_update_topology_duration_seconds_sum{context_type='live',source='topology-processor'}[10m])"
    }
   ]
  },
  {
   "title": "Projected Topology Stats Latency",
   "type": "graph",
   "description": "See https://vmturbo.atlassian.net/wiki/display/Home/XL+200k+Performance+Thought for what this means.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "end-to-end latency" }
   ],
   "targets": [
    {
     "expr": "delta(tp_broadcast_duration_seconds_sum{source='topology-processor'}[10m])"
    },
    {
     "expr": "delta(tp_discovery_duration_seconds_sum{source='topology-processor'}[10m])"
    },
    {
     "expr": "delta(mkt_analysis_duration_seconds_sump[10m])"
    },
    {
     "expr": "delta(history_update_topology_duration_seconds_sum{context_type='live',topology_type='source'}[10m])"
    },
    { "expr": "history_update_topology" }
   ]
  },
  {
   "title": "Price Index Stats Latency",
   "type": "graph",
   "description": "See https://vmturbo.atlassian.net/wiki/display/Home/XL+200k+Performance+Thought for what this means.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s", "label": "end-to-end latency" }
   ],
   "targets": [
    {
     "expr": "delta(tp_discovery_duration_seconds_sum{source='topology-processor'}[10m])"
    },
    {
     "expr": "delta(tp_broadcast_duration_seconds_sum{source='topology-processor'}[10m])"
    },
    {
     "expr": "delta(mkt_analysis_duration_seconds_sum[10m])"
    },
    {
     "expr": "delta(history_update_topology_duration_seconds_sum{context_type='live',topology_type='source'}[10m])"
    }
   ]
  }
 ]
}