{
 "title": "Top 10 Pods Based on Memory and CPU",
 "description": "This dashboard helps to find Top 10 Pods",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Top 10 Pods based on Memory Request (Bytes)",
   "type": "graph",
   "description": "Top 10 Pods based on Memory Request (Bytes)",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,kube_pod_container_resource_requests_memory_bytes)",
     "legendFormat": "{{namespace}}.{{pod}}"
    }
   ]
  },
  {
   "title": "Top 10 Pods based on CPU Request (Cores)",
   "type": "graph",
   "description": "Top 10 Pods based on CPU Request (Cores)",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10,kube_pod_container_resource_requests_cpu_cores)",
     "legendFormat": "{{namespace}}.{{pod}}"
    }
   ]
  },
  {
   "title": "Top 10 Pods based on Memory Limits (Bytes)",
   "type": "graph",
   "description": "Top 10 Pods based on Memory Limits (Bytes)",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(kube_pod_container_resource_limits_memory_bytes{}) by (namespace,pod))",
     "legendFormat": "{{namespace}}.{{pod}}"
    }
   ]
  },
  {
   "title": "Top 10 Pods based on CPU Limits (Cores)",
   "type": "graph",
   "description": "Top 10 Pods based on CPU Limits (Cores)",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(kube_pod_container_resource_limits_cpu_cores{}) by (namespace,pod))",
     "legendFormat": "{{namespace}}.{{pod}}"
    }
   ]
  },
  {
   "title": "Top 10 Pods based on Memory Consumptions (Bytes)",
   "type": "graph",
   "description": "Top 10 Pods based on Memory Consumptions (Bytes)",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, container_memory_working_set_bytes{container_name!=\"POD\",container_name!=\"\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Pods based on CPU Consumptions (millicores)",
   "type": "graph",
   "description": "Top 10 Pods based on CPU Consumption (Cores)",
   "gridPos": { "h": 15, "w": 12, "x": 24, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(container_cpu_usage_seconds_total{container_name!=\"POD\",container_name!=\"\"}[5m])*1000)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}