apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    zone: secure
    io.kompose.service: arangodb
  name: {{ .Chart.Name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    zone: secure
    io.kompose.service: arangodb-dump
  name: {{ .Chart.Name }}-dump
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    zone: secure
    io.kompose.service: arangodb-apps
  name: {{ .Chart.Name }}-apps
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    zone: secure
    io.kompose.service: arangodb
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        zone: secure
        io.kompose.service: arangodb
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: ARANGO_ROOT_PASSWORD
          value: root
        - name: ARANGODB_DEFAULT_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 8529
        readinessProbe:
          httpGet:
            port: 8529
            path: /
        resources:
{{ toYaml .Values.resources | indent 12 }}
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /var/lib/arangodb3
          name: arangodb
        - mountPath: /var/lib/arangodb3-apps
          name: arangodb-apps
        - mountPath: /home/arangodb/arangodb-dump
          name: arangodb-dump
        - mountPath: /tmp
          name: arangodb-tmpfs0
{{- if .Values.global }}
  {{- if and .Values.global.registry .Values.global.imageUsername .Values.global.imagePassword }}
      imagePullSecrets:
      - name: turbocred
  {{- end -}}
{{- end }}
      restartPolicy: Always
      securityContext:
        fsGroup: 2000
      terminationGracePeriodSeconds: 1800
      volumes:
      - name: arangodb
        persistentVolumeClaim:
          claimName: arangodb
      - name: arangodb-apps
        persistentVolumeClaim:
          claimName: arangodb-apps
      - name: arangodb-dump
        persistentVolumeClaim:
          claimName: arangodb-dump
      - name: arangodb-tmpfs0
        emptyDir: {}
  selector:
    matchLabels:
      io.kompose.service: arangodb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    zone: secure
    io.kompose.service: arangodb
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: http-arangodb
    port: 8529
  - name: http-arangodb-dump
    port: 8599
  selector:
    io.kompose.service: arangodb
