apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgresql.fullname" . }}
  labels:
    zone: secure
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.loadBalancerIP (eq .Values.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ with .Values.service.loadBalancerSourceRanges }}
{{ toYaml . | indent 4 }}
{{- end }}
  {{- end }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if and (.Values.global) (.Values.global.externalIP) (not .Values.global.externalTimescaleDBIP) }}
  externalIPs:
    - {{ .Values.global.externalIP }}
  {{- end }}
  ports:
  - name: tcp-postgresql
    port: {{ template "postgresql.port" . }}
    targetPort: tcp-postgresql
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
{{- if .Values.global }}
  {{- if .Values.global.externalTimescaleDBName }}
  type: ExternalName
  externalName: {{ .Values.global.externalTimescaleDBName }}
  {{- end -}}
  {{- if and (not .Values.global.externalTimescaleDBName) (not .Values.global.externalTimescaleDBIP)}}
  selector:
    role: master
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- end -}}
  {{- if and (.Values.global.externalTimescaleDBIP) (not .Values.global.externalTimescaleDBName)}}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "postgresql.fullname" . }}
subsets:
  - addresses:
    - ip: {{ .Values.global.externalTimescaleDBIP | quote }}
    ports:
    - name: tcp-postgresql
      port: {{ .Values.global.externalTimescaleDBPort | default 5432 }}
  {{- end -}}
{{- end }}