apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    zone: internal
    io.kompose.service: zookeeper-data
  name: {{ .Chart.Name }}-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    zone: internal
    io.kompose.service: zookeeper
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        zone: internal
        io.kompose.service: zookeeper
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: ZOO_MY_ID
          value: "1"
        - name: ZOO_SERVERS
          value: zoo
        - name: clustermgr_host
          value: clustermgr
        - name: clustermgr_port
          value: "8080"
        - name: clustermgr_retry_delay_sec
          value: "10"
        - name: consul_host
          value: consul
        ports:
        - containerPort: 2181
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "/zookeeper-ready"
        resources:
{{ toYaml .Values.resources | indent 12 }}
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /var/lib/zoo
          name: zookeeper-data
        - mountPath: /tmp
          name: zookeeper-tmpfs0
{{- if .Values.global }}
  {{- if and .Values.global.registry .Values.global.imageUsername .Values.global.imagePassword }}
      imagePullSecrets:
      - name: turbocred
  {{- end -}}
{{- end }}
      restartPolicy: Always
      securityContext:
        fsGroup: 2000
      volumes:
      - name: zookeeper-data
        persistentVolumeClaim:
          claimName: zookeeper-data
      - name: zookeeper-tmpfs0
        emptyDir: {}
  selector:
    matchLabels:
      io.kompose.service: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  labels:
    zone: internal
    io.kompose.service: zookeeper
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: tcp-zookeeper
    port: 2181
  selector:
    io.kompose.service: zookeeper
