{{- if .Values.global.telemetry.automatic.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  aws_access_key_id: {{ (.Values.global.telemetry.secret | b64dec | fromYaml).aws_access_key_id | b64enc}}
  aws_secret_access_key: {{ (.Values.global.telemetry.secret | b64dec | fromYaml).aws_secret_access_key | b64enc}}
  plg_aws_access_key_id: {{ (.Values.global.telemetry.secret | b64dec | fromYaml).plg_aws_access_key_id | b64enc}}
  plg_aws_secret_access_key: {{ (.Values.global.telemetry.secret | b64dec | fromYaml).plg_aws_secret_access_key | b64enc}}
{{- end }}
