apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    zone: secure
    io.kompose.service: consuldata
  name: {{ .Chart.Name }}data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    zone: secure
    io.kompose.service: consul
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        zone: secure
        io.kompose.service: consul
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "consul_image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - vmt-server
        - -client=0.0.0.0
        - -ui
        env:
        - name: CONSUL_BIND_INTERFACE
          value: eth0
        ports:
        - containerPort: 8500
          name: ui-port
        - containerPort: 8400
          name: alt-port
        - containerPort: 53
          name: udp-port
        - containerPort: 443
          name: https-port
        - containerPort: 8080
          name: http-port
        - containerPort: 8301
          name: serflan
        - containerPort: 8302
          name: serfwan
        - containerPort: 8600
          name: consuldns
        - containerPort: 8300
        readinessProbe:
          httpGet:
            port: 8500
            path: /ui/
        resources:
{{ toYaml .Values.resources | indent 12 }}
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /consul/data
          name: consuldata
        - mountPath: /tmp
          name: consul-tmpfs0
{{- if .Values.global }}
  {{- if and .Values.global.registry .Values.global.imageUsername .Values.global.imagePassword }}
      imagePullSecrets:
      - name: turbocred
  {{- end -}}
{{- end }}
      restartPolicy: Always
      securityContext:
        fsGroup: 2000
      volumes:
      - name: consuldata
        persistentVolumeClaim:
          claimName: consuldata
      - name: consul-tmpfs0
        emptyDir: {}
  selector:
    matchLabels:
      io.kompose.service: consul
---
apiVersion: v1
kind: Service
metadata:
  labels:
    zone: secure
    io.kompose.service: consul
  name: {{ .Chart.Name }}
spec:
  ports:
  # the port that this service should serve on
  - name: http-consul
    port: 8500
  - name: rpc-consul
    port: 8400
  - name: tcp-serflan
    port: 8301
  - name: tcp-serfwan
    port: 8302
  - name: tcp-server
    port: 8300
  - name: udp-consuldns
    port: 8600
  selector:
    io.kompose.service: consul
