{
 "title": "Action Orchestrator Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Action Orchestrator live action plan population time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(ao_populate_store_duration_seconds_sum{namespace=\"[[namespace]]\",store_type=\"Live\"}[10m])"
    }
   ]
  },
  {
   "title": "Action Orchestrator plan action plan population time",
   "type": "graph",
   "description": "Includes time to persist all actions to the database",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(ao_populate_store_duration_seconds_sum{namespace=\"[[namespace]]\",store_type=\"Plan\"}[10m])"
    }
   ]
  },
  {
   "title": "Action Orchestrator delete plan action plan time",
   "type": "graph",
   "description": "Includes time to persist all actions to the database",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(ao_delete_plan_action_plan_duration_seconds_sum{namespace=\"[[namespace]]\"}[10m])"
    }
   ]
  },
  {
   "title": "Action Orchestrator GC Collection Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_gc_collection_seconds_sum{namespace=\"[[namespace]]\",service=\"action-orchestrator\"}[10m])"
    }
   ]
  },
  {
   "title": "Individual Run Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{namespace=\"[[namespace]]\",service=\"action-orchestrator\"}"
    }
   ]
  }
 ]
}