{
 "title": "History Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Store Live Source Topology Stats",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(history_update_topology_duration_seconds_sum{namespace=\"[[namespace]]\",topology_type=\"source\", context_type=\"live\"}[10m])"
    }
   ]
  },
  {
   "title": "Store Live Projected Topology Stats",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(history_update_topology_duration_seconds_sum{namespace=\"[[namespace]]\",topology_type=\"projected\", context_type=\"live\"}[10m])"
    }
   ]
  },
  {
   "title": "Get First Page of Entity Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(history_get_entity_stats_duration_seconds_sum{namespace=\"[[namespace]]\"}[10m])"
    }
   ]
  },
  {
   "title": "Store Live Price Index",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(history_update_price_index_duration_seconds_sum{namespace=\"[[namespace]]\",context_type=\"live\"}[10m])"
    }
   ]
  },
  {
   "title": "History GC Collection Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_gc_collection_seconds_sum{namespace=\"[[namespace]]\",service=\"history\"}[10m])"
    }
   ]
  },
  {
   "title": "History Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{namespace=\"[[namespace]]\",service=\"history\"}"
    }
   ]
  }
 ]
}