{
 "title": "Kubernetes Node Resource Individual",
 "description": "Simple and straight forward Resource consumption charts for an entire Kubernetes cluster and split per cluster node",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_cpu_seconds_total{}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{kubernetes_node=~\"[[instance]]\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{kubernetes_node=~\"[[instance]]\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=~\"[[instance]]\"}-node_memory_MemAvailable_bytes{kubernetes_node=~\"[[instance]]\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=~\"[[instance]]\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Node Disk_IO Now",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_disk_io_now{kubernetes_node=~\"[[instance]]\"})"
    }
   ]
  },
  {
   "title": "Node File_System Available (Bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{kubernetes_node=~\"[[instance]]\"})"
    }
   ]
  }
 ]
}