{
 "title": "Market Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Market analysis runtime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mkt_analysis_duration_seconds{namespace=\"[[namespace]]\"}"
    }
   ]
  },
  {
   "title": "Market creation runtime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mkt_economy_build_duration_seconds{namespace=\"[[namespace]]\"}"
    }
   ]
  },
  {
   "title": "Market Convert From Traders Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_testName",
     "expr": "mkt_economy_convert_from_traders_duration_seconds{namespace=\"[[namespace]]\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "testName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mkt_economy_convert_from_traders_duration_seconds",
     "query": "SELECT mean(\"value\") FROM \"mkt_economy_convert_from_traders_duration_seconds\" WHERE (\"testName\" = 'test200kTopology') AND $timeFilter GROUP BY time($__interval), \"testName\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "testName", "operator": "=", "value": "test200kTopology" }
     ]
    }
   ]
  },
  {
   "title": "Market GC Collection Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_gc_collection_seconds_sum{namespace=\"[[namespace]]\",service=\"market\"}[10m])"
    }
   ]
  },
  {
   "title": "Market Individual Run memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{namespace=\"[[namespace]]\",service=\"market\"}"
    }
   ]
  }
 ]
}