{
 "title": "Messaging Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "interval",
    "query": "1m,10m,15m,20m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "service", "label": "component", "query": "label_values(service)" }
  ]
 },
 "panels": [
  {
   "title": "Total Bytes Produced",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(messages_sent_bytes{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message Sizes (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(messages_sent_bytes{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])/delta(messages_sent{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Largest Messages (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "messages_sent_largest_bytes{namespace=\"[[namespace]]\",service=~\"$service\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "# Messages Produced (per topic)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(messages_sent{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message Send Time per Message (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(messages_sent_ms{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])/delta(messages_sent{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Broker-to-Processed Latency per Message (ms)",
   "type": "graph",
   "description": "The average total time it takes for a message to be received and processed from the moment it arrives at the broker",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(messages_received_processing_ms_sum{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])/delta(messages_received_processing_ms_count{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval]) \n+ delta(messages_received_latency_ms{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])/delta(messages_received{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval]) \n+ delta(messages_received_enqueued_ms_sum{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])/delta(messages_received_enqueued_ms_count{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])",
     "legendFormat": "{{service}} ({{topic}})"
    }
   ]
  },
  {
   "title": "Total Bytes Consumed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(messages_received_bytes{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])",
     "legendFormat": "{{service}} ({{topic}})"
    }
   ]
  },
  {
   "title": "Consumer Latency per Message (ms)",
   "type": "graph",
   "description": "The time difference between the message timestamp and when the message was enqueued for processing in a component.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(messages_received_latency_ms{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])/delta(messages_received{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])",
     "legendFormat": "{{service}} ({{topic}})"
    }
   ]
  },
  {
   "title": "Consumer Queue Time per Message (ms)",
   "type": "graph",
   "description": "The average time a message spent enqueued for processing in a consumer",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(messages_received_enqueued_ms_sum{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])/delta(messages_received_enqueued_ms_count{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])",
     "legendFormat": "{{service}} ({{topic}})"
    }
   ]
  },
  {
   "title": "Consumer Processing Time per Message (ms)",
   "type": "graph",
   "description": "The average time a message spent in processing per message x topic",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(messages_received_processing_ms_sum{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])/delta(messages_received_processing_ms_count{namespace=\"[[namespace]]\",service=~\"$service\"}[$interval])",
     "legendFormat": "{{service}} ({{topic}})"
    }
   ]
  }
 ]
}