{
 "title": "Repository Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Repository store topology",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(repo_update_topology_duration_seconds_sum{namespace=\"[[namespace]]\",topology_type=\"source\"}[10m])",
     "legendFormat": "{{topology_type}}"
    },
    {
     "expr": "delta(repo_update_topology_duration_seconds_sum{namespace=\"[[namespace]]\",topology_type=\"projected\"}[10m])",
     "legendFormat": "{{topology_type}}"
    }
   ]
  },
  {
   "title": "Repository fetch global supply chain",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(repo_global_supply_chain_duration_seconds_sum{namespace=\"[[namespace]]\"}[10m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Repository fetch single-source supply chain (Datacenter start)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(repo_single_source_supply_chain_duration_seconds_sum{namespace=\"[[namespace]]\"}[10m])"
    }
   ]
  },
  {
   "title": "Repository GC Collection Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_gc_collection_seconds_sum{namespace=\"[[namespace]]\",service=\"repository\"}[10m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Repository java memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{namespace=\"[[namespace]]\",service=\"repository\"}",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Repository container memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{namespace=\"[[namespace]]\",name=~\"^k8s_repository.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}