{
 "title": "Statistical Summary",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Market analysis duration",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mkt_analysis_duration_seconds{namespace=\"[[namespace]]\"}"
    }
   ]
  },
  {
   "title": "Market construction duration",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mkt_economy_build_duration_seconds{namespace=\"[[namespace]]\"}"
    }
   ]
  },
  {
   "title": "Market analysis std deviations",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "mkt_analysis_duration_seconds_sum{namespace=\"[[namespace]]\"}"
    }
   ]
  },
  {
   "title": "Topology Processor Broadcast duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "tp_broadcast_duration_seconds_sum{namespace=\"[[namespace]]\"}"
    }
   ]
  },
  {
   "title": "Discovery Duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "tp_discovery_duration_seconds_sum{namespace=\"[[namespace]]\"}"
    }
   ]
  },
  {
   "title": "Action Orchestrator live action plan population duration",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "ao_populate_store_duration_seconds_sum{namespace=\"[[namespace]]\",store_type=\"Live\"}"
    }
   ]
  },
  {
   "title": "Action Orchestrator plan action plan population duration",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "ao_populate_store_duration_seconds_sum{namespace=\"[[namespace]]\",store_type=\"Plan\"}"
    }
   ]
  }
 ]
}