{
 "title": "10 Project/NameSpace Based on Memory and CPU",
 "description": "This dashboard helps to find Top 10 Namespaces \n1) using Kubernetes cluster RAM and CPU\n2) top namespace request RAM and CPU\n3) top 10 namespace limit RAM and CPU\n\nThis dashboard helps sysadmin finding Top 10 Memory Intensive Namespaces",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Top 10 Namespaces based on Memory Consumption (bytes)",
   "type": "graph",
   "description": "Top 10 Namespaces based on Memory Consumption (bytes)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(container_memory_working_set_bytes{container!=\"POD\",container!=\"\"}) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Top 10 Namespaces based on CPU Consumption (millicores)",
   "type": "graph",
   "description": "Top 10 Namespaces based on CPU Consumption (millicores)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[5m]) * 1000) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Top 10 Namespaces based on Memory Requests (bytes)",
   "type": "graph",
   "description": "Top 10 Namespaces based on Memory Requests (bytes)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(kube_pod_container_resource_requests_memory_bytes) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Top 10 Namespaces based on CPU Request (millicores)",
   "type": "graph",
   "description": "Top 10 Namespaces based on CPU Request (millicores)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(kube_pod_container_resource_requests_cpu_cores * 1000) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Top 10 Namespaces based on Memory Limits (bytes)",
   "type": "graph",
   "description": "Top 10 Namespaces based on Memory Limits (bytes)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(kube_pod_container_resource_limits_memory_bytes) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Top 10 Namespaces based on CPU Limit (millicores)",
   "type": "graph",
   "description": "Top 10 Namespaces based on CPU Limit (millicores)",
   "gridPos": { "h": 10, "w": 12, "x": 24, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(kube_pod_container_resource_limits_cpu_cores * 1000) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}