{
 "title": "Top 10 Containers Based on Memory, CPU, IO and Network",
 "description": "This dashboard helps to find Top 10 Containers",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Top 10 Containers based on Memory Usage (Bytes)",
   "type": "graph",
   "description": "Top 10 Containers based on Memory Usage (Bytes)",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,container_memory_working_set_bytes{container!=\"POD\",container!=\"\"})",
     "legendFormat": "{{namespace}}.{{pod}}.{{container}}"
    }
   ]
  },
  {
   "title": "Top 10 Containers based on CPU Usage (millicores)",
   "type": "graph",
   "description": "Top 10 Containers based on CPU Usage (Seconds)",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[5m])*1000)",
     "legendFormat": "{{namespace}}.{{pod}}.{{container}}"
    }
   ]
  },
  {
   "title": "Top 10 Containers based on Current IOs",
   "type": "graph",
   "description": "Top 10 Containers based on Current IOs",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{container!=\"\"}[5m])+rate(container_fs_reads_bytes_total{container!=\"\"}[5m]) > 0",
     "legendFormat": "{{namespace}}.{{pod}}.{{container}}"
    }
   ]
  },
  {
   "title": "Top 10 Containers based on FileSystem Usage (Bytes)",
   "type": "graph",
   "description": "Top 10 Containers based on FileSystem Usage (Bytes)",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,container_fs_usage_bytes{container!=\"POD\",container!=\"\"})",
     "legendFormat": "{{namespace}}.{{pod}}.{{container}}"
    }
   ]
  },
  {
   "title": "Top 10 Containers Based On Network Transmit (Bytes)",
   "type": "graph",
   "description": "Top 10 Containers Based On Network Transmit (Bytes)",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(rate(container_network_transmit_bytes_total{name!=\"\"}[5m])) by (namespace,pod))",
     "legendFormat": "{{namespace}}.{{pod}}"
    }
   ]
  },
  {
   "title": "Top 10 Containers Based On Network receive (Bytes)",
   "type": "graph",
   "description": "Top 10 Containers Based On Network receive (Bytes)",
   "gridPos": { "h": 15, "w": 12, "x": 24, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(rate(container_network_receive_bytes_total{name!=\"\"}[5m])) by (namespace,pod))",
     "legendFormat": "{{namespace}}.{{pod}}"
    }
   ]
  }
 ]
}