{
 "title": "Topology Processor Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Topology Processor Discovery Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(tp_discovery_duration_seconds_sum{namespace=\"[[namespace]]\"}[10m])"
    }
   ]
  },
  {
   "title": "Topology Processor Broadcast Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(tp_broadcast_duration_seconds_sum{namespace=\"[[namespace]]\"}[10m])"
    }
   ]
  },
  {
   "title": "Topology Processor Pipeline Stages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(tp_broadcast_pipeline_duration_seconds_sum{namespace=\"[[namespace]]\"}[10m])"
    }
   ]
  },
  {
   "title": "Topology Processor GC Collection Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_gc_collection_seconds_sum{namespace=\"[[namespace]]\",service=\"topology-processor\"}[10m])"
    }
   ]
  },
  {
   "title": "Topology Processor Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{namespace=\"[[namespace]]\",service=\"topology-processor\"}"
    }
   ]
  }
 ]
}