apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    zone: secure
    io.kompose.service: influxdb
  name: {{ .Chart.Name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    zone: secure
    io.kompose.service: influxdb-dump
  name: {{ .Chart.Name }}-dump
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    zone: secure
    io.kompose.service: influxdb
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        zone: secure
        io.kompose.service: influxdb
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: METRON_ENABLED
            value: "true"
          # Uncomment to specify the dump interval for influx. Default is once per day if unspecified.
          #- name: INFLUX_DUMP_INTERVAL_SECONDS
          #  value: 300
        ports:
        - containerPort: 8086
        readinessProbe:
          tcpSocket:
            port: 8086
        resources:
{{ toYaml .Values.resources | indent 12 }}
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb
        - mountPath: /home/influxdb/influxdb-dump
          name: influxdb-dump
        - mountPath: /tmp
          name: influxdb-tmpfs0
{{- if .Values.global }}
  {{- if and .Values.global.registry .Values.global.imageUsername .Values.global.imagePassword }}
      imagePullSecrets:
      - name: turbocred
  {{- end -}}
{{- end }}
      restartPolicy: Always
      securityContext:
        fsGroup: 2000
      volumes:
      - name: influxdb
        persistentVolumeClaim:
          claimName: influxdb
      - name: influxdb-dump
        persistentVolumeClaim:
          claimName: influxdb-dump
      - name: influxdb-tmpfs0
        emptyDir: {}
  selector:
    matchLabels:
      io.kompose.service: influxdb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    zone: secure
    io.kompose.service: influxdb
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: http-influxdb
    port: 8086
  - name: rpc-influxdb-dump
    port: 8088
  selector:
    io.kompose.service: influxdb
